### ISSUE TITLE
Differences between Github and NuGet versions

### ISSUE THREAD

**Issue by Fonta88** [iHomeSoft/OmronFinsTCP.Net#3]
Hi,

I'm trying to read PLC addresses with your library, it works very well. I found a differnce between the code in this repository and those on NuGet. In particular I found that the enum PlcMemory has new entries, that probably means that new memory areas are supported for reading and writing. 
Since the last commit was on october 2019 and the NuGet version was released on november 2015, I need to know if the more recent changes will be released on NuGet soon.

Are further updates in pipeline or this library won't be updated no more?

My last doubt is about license of this library. I cannot find any info neither on GitHub nor in NuGet nor in your website. Please can you provide me informations about this aspect?

Thanks in advance
Paolo

**Comment by iHomeSoft** [comment]
You can use it completely freely, personally, commercial or republished.
There is no update on nuget, you can compile it yourself.

Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fonta88"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 晚上9:21
收件人: "iHomeSoft/OmronFinsTCP.Net"<OmronFinsTCP.Net@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [iHomeSoft/OmronFinsTCP.Net] Differences between Github and NuGet versions (#3)





 
Hi,
 
I'm trying to read PLC addresses with your library, it works very well. I found a differnce between the code in this repository and those on NuGet. In particular I found that the enum PlcMemory has new entries, that probably means that new memory areas are supported for reading and writing.
 Since the last commit was on october 2019 and the NuGet version was released on november 2015, I need to know if the more recent changes will be released on NuGet soon.
 
Are further updates in pipeline or this library won't be updated no more?
 
My last doubt is about license of this library. I cannot find any info neither on GitHub nor in NuGet nor in your website. Please can you provide me informations about this aspect?
 
Thanks in advance
 Paolo

**Comment by Fonta88** [comment]
Ok, thanks for your response!

BR
Paolo
